Ajout d'un champ 'isTest' pour sauvegarder une BAL de démonstration
etalab/api-bal pull request #255
Opened 2020-11-16 14:11 UTC by GllmR

2020-11-16 15:20 UTC, tmerlier requested changes

2020-11-16 15:20 UTC, tmerlier commented on lib/models/base-locale.js
> +  isTest: Joi.boolean().default(false)
`isTest` n'est pas obligatoire.

2020-11-16 16:28 UTC, tmerlier approved these changes

2020-11-16 19:43 UTC, jdesboeufs requested changes
Il faut soit tout reprendre soit rester sur le paradigme de @tmerlier avec deux schémas, démo et normal.

2020-11-17 16:21 UTC, jdesboeufs commented on lib/routes/index.js
> +app.route('/bases-locales/test/:baseLocaleId')
Je trouve pas l'URL très explicite.

2020-11-17 16:30 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const changes = validPayload(payload, createSchema)
Pourquoi doit-on repasser tout le payload ?

2020-11-17 16:30 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    nom: changes.nom || 'Base Locale',
Nom peu pertinent.
On a une convention sur Adresses de XXX si une seule commune.

2020-11-17 16:32 UTC, jdesboeufs commented on lib/models/base-locale.js
> +async function createBaseLocaleTest() {
Je vois pas trop l'intérêt d'avoir un point d'entrée séparé.

2020-11-24 21:23 UTC, jdesboeufs commented
Rendu obsolète par #257

2020-11-24 21:23 UTC, closed without merging