[WIP] Remplace "isTest" par le status "demo"
etalab/api-bal pull request #257
Opened 2020-11-23 16:33 UTC by tmerlier

- POST `/bases-locales/create-demo` : Création d'un Base Adresse Locale de démonstration 
### body
```
{}
```
### Response:
```
{
  "nom": "Base Adresse Locale [DEMO]",
  "status": "demo"
  "token": 'token',
  "communes": [],
  "_updated": "2020-11-23T16:31:35.106Z",
  "_created": "2020-11-23T16:31:35.106Z" 
}
```

----

- POST `/bases-locales/:baseLocaleId/transform-to-draft` : Transforme une Base Adresse Locale de démonstration en Base Adresse Locale avec un statut `brouillon`
### body
```
{
   "nom": "Base Locale de Breux-sur-Avre",
   "email": "email@me.fr"
}
```
### Response
```
{
  "nom": "Base Locale de Breux-sur-Avre",
  "status": "draft"
  "token": 'token',
  "emails": ["email@me.fr"],
  "communes": [],
  "_updated": "2020-11-23T16:31:35.106Z",
  "_created": "2020-11-23T16:31:35.106Z" 
}
```

2020-11-23 16:34 UTC, tmerlier commented
En attente de l'ouverture de la PR correspondante sur le front.

2020-11-23 17:05 UTC, jdesboeufs requested changes

2020-11-23 17:05 UTC, jdesboeufs commented on lib/models/base-locale.js
> +async function createDemo() {
Paramètres `commune` et `populate` attendus

2020-11-24 14:40 UTC, jdesboeufs commented on lib/models/__tests__/base-locale.mongo.js
> +    communes: [],
Une BAL de démo contient forcément une commune non ?

2020-11-24 14:44 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  commune: Joi.string().min(3).max(5).required(),
Un peu useless, par contre la vérification que la commune existe serait plus pertinent, on le fait bien dans l'URL classique ;)

2020-11-24 14:45 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  nom: Joi.string().max(200).allow(null),
Duplication de code

2020-11-24 14:47 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    const response = await got(`https://geo.api.gouv.fr/communes/${codeCommune}`, {responseType: 'json'})
Inutile. Utiliser `@etalab/decoupage-administratif` et `lib/cog`

2020-11-24 14:48 UTC, jdesboeufs commented on lib/models/base-locale.js
> +
Vérifier que le `status` actuel est bien `demo`.

2020-11-24 14:48 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const email = createBalCreationNotificationEmail({baseLocale: baseLocaleChanges})
Utiliser la BAL plutôt que des champs étrangers.

2020-11-24 14:49 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const email = createBalCreationNotificationEmail({baseLocale: baseLocaleChanges})
donc value

2020-11-24 14:50 UTC, jdesboeufs commented on lib/routes/index.js
> +      return res.status(403).send(403, {code: 403, message: 'Forbidden update of demo base locale'})
On a pas des erreurs en français normalement ?

2020-11-24 14:50 UTC, jdesboeufs commented on lib/routes/index.js
> +      return res.status(403).send(403, {code: 403, message: 'Forbidden update of demo base locale'})
La signature de send est incorrecte.

2020-11-24 14:51 UTC, jdesboeufs commented on lib/routes/index.js
> +    const baseLocale = await BaseLocale.transformToDraft(req.baseLocale._id, req.body)
Tu pourrais passer `req.baseLocale` en fait.

2020-11-24 21:24 UTC, jdesboeufs approved these changes

2020-11-24 21:25 UTC, jdesboeufs commented
Migration à réaliser :
```
db.bases_locales.updateMany({isTest: true}, {$set: {status: 'demo'}, $unset: {isTest: 1}})
```

2020-11-25 09:08 UTC, merged