Ajout du modèle Commune
etalab/api-bal pull request #264
Opened 2021-01-15 18:03 UTC by tmerlier

Ajout du modèle `Commune` et migre le `status` du modèle `BaseLocale` à `Commune`.

Cette modification vient préparer le terrain d'une publication à l'échelle communale.

2021-01-22 14:22 UTC, jdesboeufs requested changes

2021-01-22 14:22 UTC, jdesboeufs commented on lib/routes/index.js
> +    res.send(BaseLocale.getCommune(req.baseLocale._id, req.params.codeCommune))
Missing `await`

2021-01-22 14:22 UTC, jdesboeufs commented on lib/routes/index.js
> +    const commune = await BaseLocale.updateCommuneStatus(req.baseLocale, req.params.codeCommune, 'draft')
Missing status check

2021-01-22 14:22 UTC, jdesboeufs commented on lib/routes/index.js
> +    const commune = await BaseLocale.updateCommuneStatus(req.baseLocale, req.params.codeCommune, 'ready-to-publish')
Missing status check

2021-01-22 14:22 UTC, jdesboeufs commented on lib/routes/index.js
> +app.route('/bases-locales/:baseLocaleId/communes/:codeCommune/publish')
On a rien de câblé. L'utilisateur ne peut pas décider lui-même que sa BAL est publiée

2021-01-22 14:22 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    communes: []
Champ à supprimer

2021-01-22 14:22 UTC, jdesboeufs commented on lib/models/base-locale.js
>      communes: [commune],
À supprimer ici

2021-01-22 14:22 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    {returnOriginal: false}
Option inutile puisque la valeur de retour n'est pas utilisée

2021-01-22 14:22 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  return mongo.db.collection('bases_locales').find({communes: {$elemMatch: {code: {$in: codesCommunes}}}}).toArray()
Cette valeur n'a pas à être portée par la collection `bases_locales`

2021-01-22 14:22 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  if (communes.length > 0) {
Dans ce cas utilises `.count` au lieu de `.find` + `toArray`

2021-01-22 14:22 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  if (!commune) {
Pas cohérent avec nos autres getters qui renvoient `undefined`.

2021-04-27 14:11 UTC, tmerlier commented
Remplacé par #273 Collection Commune

2021-04-27 14:11 UTC, closed without merging