[WIP] Ajout de la collection toponymes, référence possible dans la collection numeros
etalab/api-bal pull request #269
Opened 2021-03-12 15:44 UTC by cedric-famibelle-pronzola

## Points d'accès
### `/bases-locales/{id}/communes/codeCommune/toponymes`
- `POST` : Créer un toponyme
- `GET` : Lister les toponymes

### `/toponymes/{id}`
- `GET` : Retourner les informations concernant un toponyme
- `PUT` : Modifier un toponyme
- `DELETE` : Supprimer un toponyme

### Toponyme
| Attributs | Éditable | Commentaire
| --------- | -------- | -----------
| _id      | ❌ | Identifiant unique|
| _created      | ❌ | Date de création|
| _updated | ❌ | Date de mise à jour|
| nom       | ✅       | Nom du toponyme *
| positions | ✅       | Tableau de positions
| commune| ❌ | Commune de rattachement du toponyme|
| _bal | ❌ | Référence |

 \* Champs obligatoires

### Numero (modifications liées à la PR)

| Attributs | Éditable | Commentaire
| --------- | -------- | -----------
| toponyme | ✅       | Référence

2021-03-12 17:22 UTC, GllmR approved these changes

2021-04-20 14:58 UTC, jdesboeufs requested changes
Migration pas suffisamment solide

2021-04-20 19:32 UTC, jdesboeufs requested changes

2021-04-20 19:32 UTC, jdesboeufs commented on lib/models/toponyme.js
> +  toponyme.commune = codeCommune
Vérifier que la commune est dans la BAL

2021-04-20 19:32 UTC, jdesboeufs commented on lib/models/toponyme.js
> +  nom: Joi.string().min(1).max(200),
Idem

2021-04-20 19:32 UTC, jdesboeufs commented on lib/models/toponyme.js
> +    payload.nom = cleanNom(payload.nom)
Vu !!

2021-04-20 19:32 UTC, jdesboeufs commented on lib/models/toponyme.js
> +    position.createSchema
Idem

2021-04-20 19:32 UTC, jdesboeufs commented on lib/models/toponyme.js
> +      toponyme.commune = t.commune
À quel moment la commune est-elle contrôlé ? Est-elle dans la BAL ?

2021-04-20 19:32 UTC, jdesboeufs commented on lib/models/toponyme.js
> +    _bal: idBal,
Index ?

2021-04-20 19:32 UTC, jdesboeufs commented on lib/models/toponyme.js
> +  const {value} = await mongo.db.collection('toponymes').findOneAndDelete({
Il vaut mieux modifier les numéros avant la suppression du toponyme (consistante).

2021-04-20 19:32 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +    commune: voieRow.cle_interop.slice(0, 5),
Ce champ existe déjà en sortie du validateur. Inutile de l'extraire de cette façon.

2021-04-20 19:32 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +function createLieuDit(idToponyme, toponymeRow, positionsRows = []) {
Terminologie LieuDit ?? versus Hameau ?
Il faut conserver Toponyme partout.

2021-04-20 19:32 UTC, jdesboeufs commented on lib/populate/extract-csv.js
> +function formatHameaux(hameaux) {
Nom inadapté.

2021-04-21 10:17 UTC, jdesboeufs commented on lib/export/geojson.js
> +    idToponyme: n.toponyme,
https://github.com/etalab/api-bal/issues/275

2021-04-21 10:17 UTC, jdesboeufs commented on lib/export/geojson.js
> +module.exports = {transformToGeoJSON, numeroVoieToAdresseFeature}
https://github.com/etalab/api-bal/issues/275

2021-04-21 10:29 UTC, jdesboeufs commented on lib/models/toponyme.js
> +  toponyme.commune = codeCommune
C'est défini en amont, dans `importFile` ou implicitement via `populateCommune`

2021-04-21 10:31 UTC, jdesboeufs commented on lib/models/toponyme.js
> +      toponyme.commune = t.commune
C'est défini en amont, dans `importFile` ou implicitement via `populateCommune`

2021-04-26 22:27 UTC, jdesboeufs approved these changes

2021-04-26 22:27 UTC, merged