Collection  communes
etalab/api-bal pull request #273
Opened 2021-03-19 13:19 UTC by tmerlier

## Contexte
Actuellement le `status` de publication est lié à la `base_locale` ce qui empêche la publication par commune. Cette PR prépare les futures développement permettant cette fonctionnalité.

## Modification
Suppression du champ `communes` de la collection `bases_locales`. Ce champ contenait la liste des codes communes de la base locale
`BaseLocale.communes = ['xxxxx', 'xxxxx', …]`

## Création
Nouvelle collection `communes`

```
  {
    code: 'xxxxx',
    _bal: mongo.parseObjectID
  }
```

2021-05-06 20:21 UTC, jdesboeufs requested changes
Review partielle

2021-05-06 20:21 UTC, jdesboeufs commented on migration/2021-03-19-communes-collection.js
> +      await Promise.all(
Utiliser `insertMany` à la place

2021-05-06 20:21 UTC, jdesboeufs commented on lib/util/mongo.js
> +    await this.db.collection('numeros').createIndex({toponymes: 1})
`toponyme` 😬

2021-05-06 20:21 UTC, jdesboeufs commented on migration/2021-03-19-communes-collection.js
> +  basesLocales.forEach(async ({_id, communes}) => {
Il faut utiliser `for ... of` car forEach fait perdre le contrôle sur l'appel asynchrone.
`Promise.all` est aussi une option, mais trop agressif pour MongoDB.
Il y a aussi bluebird.

2021-05-07 16:04 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    throw new Error('Commune non associée à la base locale')
"Cette Base Adresse Locale ne contient pas de commune. Il n'est pas possible de la convertir."

2021-05-07 16:06 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const communes = await mongo.db.collection('communes').find({code: {$in: codesCommunes}}).toArray()
Tu peux directement utiliser `mongo.db.collection('communes').distinct('_bal', {code: {$in: codesCommunes}})`. Cela te renvoie le tableau des identifiants de BAL.

2021-05-07 16:07 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  return commune
Changement dans l'API. Auparavant on retournait la BAL et pas l'objet commune.

2021-05-07 16:09 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const {value} = await mongo.db.collection('communes').findOneAndDelete({
Tu n'as pas besoin de récupérer la valeur. Un simple `deleteOne` suffit.
Tu as l'information de si la suppression a été effective ou pas dans la réponse.

2021-05-07 16:12 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    mongo.db.collection('communes').deleteMany({_bal: mongo.parseObjectID(id)})
Ça me parait hyper dangereux x)

2021-05-20 09:36 UTC, cedric-famibelle-pronzola commented on lib/models/base-locale.js
> +    mongo.db.collection('communes').deleteMany({_bal: mongo.parseObjectID(id)})
Pourquoi ?
On entre dans cette condition lors de la suppression d'une BAL ou de l'import d'un fichier.

2021-09-03 15:24 UTC, closed without merging