Améliration de la méthode fetchByToponyme et de la route y faisant référence
etalab/api-bal pull request #276
Opened 2021-04-29 16:10 UTC by cedric-famibelle-pronzola

- la route `/toponymes/:toponymeId/numeros` renvoie la liste des numéros avec un objet voie au lieu d'un "array"
- renvoie également un format étendu des numéros avec l'ajout de `Numero.expandModel(numero)`
- mise à jour des tests liés à la méthode

2021-04-30 08:03 UTC, tmerlier requested changes

2021-04-30 08:03 UTC, tmerlier commented on lib/routes/__tests__/numeros.js
> +  t.is(Object.keys(body[0]).length, KEYS.length)
Utilise `mongo.parseObjectID` à la place de `toHexString`.

2021-04-30 08:03 UTC, tmerlier commented on lib/models/numero.js
> +      preserveNullAndEmptyArrays: true
@jdesboeufs est-ce que tu valide ?

2021-04-30 09:29 UTC, jdesboeufs commented on lib/models/numero.js
> +      preserveNullAndEmptyArrays: true
Ça sert à quoi ? Je vois pas trop l'intérêt ici.

2021-04-30 09:29 UTC, jdesboeufs commented on lib/routes/__tests__/numeros.js
> +  t.is(Object.keys(body[0]).length, KEYS.length)
Non c'est bon ce qu'il a fait

2021-04-30 09:31 UTC, cedric-famibelle-pronzola commented on lib/models/numero.js
> +      preserveNullAndEmptyArrays: true
avant, la propriété "voie" retournait un array, alors qu'il y a toujours une seule voie.
ça permet de retourner un object voie à la place.

2021-05-04 19:15 UTC, jdesboeufs requested changes

2021-05-04 19:15 UTC, jdesboeufs commented on lib/models/numero.js
> +  for (const numero of numerosWithToponyme) {
Un map serait plus adapté plutôt que modifier l'objet `numero` dans un for of.
L'immutabilité des objets doit toujours être préférée quand c'est possible

2021-05-04 19:15 UTC, jdesboeufs commented on lib/models/numero.js
> +  const voies = await mongo.db.collection('voies').find({_id: {$in: numerosWithToponyme.map(r => r.voie)}}).toArray()
La liste des identifiants de voies devrait être compactée avant d'être passée dans la requête :
`uniq(compact(...))`

2021-05-05 10:04 UTC, jdesboeufs approved these changes

2021-05-05 13:44 UTC, merged