Ajout des parcelles dans les numéros
etalab/api-bal pull request #279
Opened 2021-05-18 08:04 UTC by GllmR

- Ajout d'un champ `parcelles` sur les numéros, permettant de lier une ou plusieurs parcelles cadastrales à une adresse.

- Ajout et mise à jour des tests pour la gestion des parcelles.

2021-05-18 09:45 UTC, tmerlier requested changes

2021-05-18 09:45 UTC, tmerlier commented on lib/export/csv-bal.js
> +          parcelles: n.parcelles ? n.parcelles : null,
`parcelles: n.parcelles` est suffisant.

2021-05-18 09:45 UTC, tmerlier commented on lib/export/csv-bal.js
> +        parcelles: n.parcelles ? n.parcelles : null
`parcelles: n.parcelles` est suffisant.

2021-05-18 09:45 UTC, tmerlier commented on lib/export/csv-bal.js
> +          parcelles: t.parcelles ? t.parcelles : null,
`parcelles: n.parcelles` est suffisant.

2021-05-18 09:45 UTC, tmerlier commented on lib/export/csv-bal.js
> +        parcelles: t.parcelles ? t.parcelles : null
`parcelles: n.parcelles` est suffisant.

2021-05-18 09:45 UTC, tmerlier commented on lib/models/__tests__/numero.mongo.js
> +})
Pour les tests, il est préférable de tester des valeurs "brutes" quand cela est possible. Cela permet de limiter des effets indésirables comme une mutation imprévu de la variable testée.

```
  const _idVoie = new mongo.ObjectID()
  await mongo.db.collection('voies').insertOne({_idVoie})
  const numero = await Numero.create(
    _idVoie,
    {numero: 42, parcelles: ['12345000AA0001', '12345000AA0002']}
  )

  t.deepEqual(numero.parcelles, ['12345000AA0001', '12345000AA0002'])
```

2021-05-18 09:45 UTC, tmerlier commented on lib/models/__tests__/numero.mongo.js
> +  const parcelles = ['12345000aa0001']
Cette variable n'a pas de justification.

2021-05-18 09:45 UTC, tmerlier commented on lib/populate/__tests__/extract-csv.js
> +const csvFile = `cle_interop;uid_adresse;voie_nom;lieudit_complement_nom;numero;suffixe;commune_nom;position;long;lat;x;y;cad_parcelles;source;date_der_maj
@jdesboeufs Est-ce que cette solution te parait satisfaisante pour remplacer la lecture d'un fichier ?

2021-05-18 09:45 UTC, tmerlier commented on lib/populate/__tests__/extract-csv.js
> +  t.is(isValid, true)
`t.true`

2021-05-18 09:45 UTC, tmerlier commented on lib/populate/extract-csv.js
> +          parcelles: numeroRows[0].cad_parcelles || null,
`parcelles: numeroRows[0].cad_parcelles`

2021-05-18 09:45 UTC, tmerlier commented on lib/populate/extract-csv.js
> +        parcelles: numeroRows[0].cad_parcelles || null,
`parcelles: numeroRows[0].cad_parcelles`

2021-05-18 09:45 UTC, tmerlier commented on lib/populate/extract-csv.js
> +          parcelles: numeroRows[0].cad_parcelles || null,
@jdesboeufs Les toponymes peuvent-ils avoir des parcelles assignées ?

2021-05-18 13:36 UTC, tmerlier approved these changes

2021-05-18 19:27 UTC, jdesboeufs commented on lib/populate/__tests__/extract-csv.js
> +const csvFile = `cle_interop;uid_adresse;voie_nom;lieudit_complement_nom;numero;suffixe;commune_nom;position;long;lat;x;y;cad_parcelles;source;date_der_maj
Oui pour l’API c’est suffisant. Les malformations on les teste dans le validateur.

2021-05-18 19:32 UTC, jdesboeufs commented on lib/populate/__tests__/extract-csv.js
> +  t.deepEqual(numeros[0].parcelles, ['123450000QQ666', '123450000KK666'])
On peut quand même prendre un exemple non erroné et éventuellement améliorer la regex.
CCCCCPPPSSNNNN
CCCCC = 5 chiffres sauf A ou B possibles en deuxième position (Corse)
PPP = 3 chiffres
SS = 2 chiffres ou lettres
NNNN = 4 chiffres

2021-05-18 19:34 UTC, jdesboeufs commented on lib/populate/__tests__/extract-csv.js
> +test('import CSv file', async t => {
Typo

2021-05-18 19:40 UTC, jdesboeufs commented
Dans extract-csv on ajoute les parcelles aux toponymes, mais ce n’est pas prévu dans le model (tu as fait juste Numero).
Il faut choisir, sachant que le format CSV le permet.

2021-05-19 14:25 UTC, tmerlier requested changes
Quelques tests pour les `parcelles` pour les toponymes seraient les bienvenus.

Je en vois rien concernant l'import/export des toponymes et des parcelles. Notre gestion actuelle fait l'affaire ?

2021-05-20 12:48 UTC, tmerlier approved these changes

2021-05-21 20:54 UTC, jdesboeufs approved these changes

2021-05-26 15:39 UTC, tmerlier requested changes

2021-05-26 15:39 UTC, tmerlier commented on lib/models/base-locale.js
> +async function getUniqParcelles(balId, codeCommune) {
`getAssignedParcelles`

2021-05-27 15:35 UTC, tmerlier requested changes

2021-05-27 15:35 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +  t.is(parcelles.length, 4)
Il faut avant vérifier le contenu de `parcelles` et pas seulement son nombre d'item.

2021-05-27 15:35 UTC, tmerlier commented on lib/routes/__tests__/base-locale.js
> +  t.is(body.length, 2)
Il faut avant vérifier le contenu de `parcelles` et pas seulement son nombre d'item.

2021-05-27 15:45 UTC, tmerlier approved these changes

2021-06-07 15:06 UTC, jdesboeufs requested changes

2021-06-07 15:06 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const numeroWithParcelles = await mongo.db.collection('numeros').find({_bal: mongo.parseObjectID(balId), commune: codeCommune}).toArray()
Il faut utiliser `distinct()`

2021-06-08 09:10 UTC, jdesboeufs approved these changes

2021-06-08 09:13 UTC, merged