Ajout d'une route pour vérifier si une Base Adresse Locale a déjà été publiée
etalab/api-bal pull request #282
Opened 2021-06-03 14:15 UTC by GllmR

Ajout de la route `check-if-published`, qui attend un code commune ainsi qu'une adresse mail.

Cette route retourne une Base Adresse si la commune l'a déjà publiée ainsi qu'un argument `isOwner`. 
Si l'adresse mail correspond à celle qui a été envoyée, `isOwner` sera `true`, sinon `false`.

Si aucune Base Adresse ne correspond au code commune, elle renvoie `false`.

2021-06-03 15:43 UTC, cedric-famibelle-pronzola commented on lib/routes/index.js
> +    res.status(201).send(publishedBaseLocale)
retourne la BAL avec ses données sensibles
il faudrait utiliser la méthode `filterSensitiveFields`

2021-06-03 15:43 UTC, cedric-famibelle-pronzola commented on lib/routes/index.js
> +    console.log(result)
petit oubli

2021-06-03 16:33 UTC, cedric-famibelle-pronzola commented on lib/models/base-locale.js
> +
`publishedBaseLocale` retourne un array, mais la méthode ne retourne que le premier élément.

2021-06-07 09:55 UTC, tmerlier requested changes

2021-06-07 09:55 UTC, tmerlier commented on lib/models/base-locale.js
> +  if (codeCommune) {
Si `codeCommune` n'existe pas alors il faut renvoyer une erreur.

2021-06-07 09:55 UTC, tmerlier commented on lib/models/base-locale.js
> +  }
```
    const isOwner = userEmail && publishedBaseLocale[0].emails.includes(userEmail)
    return { ...filterSensitiveFields(publishedBaseLocale[0]), isOwner:}
```

2021-06-07 09:55 UTC, tmerlier commented on lib/routes/index.js
> +app.route('/bases-locales/check-if-published')
`/bases-locales/is-published`

2021-06-07 09:55 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +  })
N'est pas utilisée.

2021-06-07 09:55 UTC, tmerlier commented on lib/models/base-locale.js
> +    const publishedBaseLocale = await mongo.db.collection('bases_locales')
Il serait préférable que l'on renvoi la liste de toutes les BAL publiée pour la commune demandée. Cela permettrait une plus grande réutilisation de cette route.

2021-06-07 09:55 UTC, tmerlier commented on lib/routes/__tests__/base-locale.js
> +  t.is(body, false)
Devrait renvoyer une erreur.

2021-06-07 09:55 UTC, tmerlier commented on lib/routes/__tests__/base-locale.js
> +
D'autre tests serait les bienvenus comme par exemple:
- BAL déjà publiée
- BAL déjà publiée + isOwner
- Pas de BAL publiée

2021-06-07 09:55 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +
D'autres tests serait les bienvenus comme par exemple:
- BAL déjà publiée
- Pas de BAL publiée

2021-06-07 10:30 UTC, GllmR commented on lib/models/__tests__/base-locale.mongo.js
> +  })
C'est pour être sûr que la fonction en renvoie pas toutes les BAL.

2021-06-07 15:23 UTC, jdesboeufs commented
On aurait pu faire un début de `search` plutôt. Ça aurait eu le mérite de servir pour la suite :)

2021-06-08 15:46 UTC, tmerlier requested changes

2021-06-08 15:46 UTC, tmerlier commented on lib/models/base-locale.js
> +  throw new Error('Code commune introuvable')
Non ici le code commune n'a pas était fourni, hors il est obligatoire.

2021-06-08 15:46 UTC, tmerlier commented on lib/models/base-locale.js
> +    return false
```
return publishedBasesLocales.map(bal => {
         const isOwner = userEmail && bal.emails.includes(userEmail)
         return {...filterSensitiveFields(bal), isOwner}
       })
```

2021-06-08 15:46 UTC, tmerlier commented on lib/models/base-locale.js
> +    return false
En partant du principe qu'il serait préférable de renvoyer une liste vide plutôt que `false`.

2021-06-14 08:42 UTC, tmerlier requested changes

2021-06-14 08:42 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +  const unpublishedBaseLocale = await BaseLocale.checkPublishedBAL(['55327'])
Pourquoi envoyer une liste de codes commune ? Il est dit sur la description que `BaseLocale.checkPublishedBAL` ne reçoit qu'un seul code.

2021-06-14 08:42 UTC, tmerlier commented on lib/models/base-locale.js
> +    return verifiedPublishedBasesLocales
```
return publishedBasesLocales.map(bal => {
       const isOwner = userEmail && bal.emails.includes(userEmail)
       return {...filterSensitiveFields(bal), isOwner}
     })
```

2021-06-14 08:45 UTC, GllmR commented on lib/models/__tests__/base-locale.mongo.js
> +  const unpublishedBaseLocale = await BaseLocale.checkPublishedBAL(['55327'])
Lors de l'import d'un fichier CSV, il est possible d'avoir plusieurs communes.
Je vais modifier la description.

2021-06-15 08:36 UTC, tmerlier requested changes

2021-06-15 08:36 UTC, tmerlier commented on lib/models/__tests__/base-locale.mongo.js
> +})
Ce test ne concerne pas la PR en cours.

2021-06-15 08:36 UTC, tmerlier commented on lib/models/base-locale.js
> +
Cette fonction ne concernant pas la PR en cours.

2021-06-15 08:36 UTC, tmerlier commented on lib/routes/__tests__/base-locale.js
> +})
Ces tests ne concernent pas la PR en cours.

2021-06-15 13:21 UTC, tmerlier requested changes

2021-06-15 13:21 UTC, tmerlier commented on lib/routes/index.js
> +  .post(w(async (req, res) => {
`get`

2021-06-15 13:21 UTC, tmerlier commented on lib/routes/__tests__/base-locale.js
> +    .send({codeCommune: '27115'})
C'est une liste `[]` qui est attendu.

C'est également valable pour les autres tests.

2021-06-15 13:21 UTC, tmerlier commented on lib/models/base-locale.js
> +async function checkPublishedBAL(codeCommune, userEmail) {
`codeCommune` -> `codesCommune` ou `communes`

2021-06-16 13:35 UTC, cedric-famibelle-pronzola approved these changes

2021-06-17 08:59 UTC, tmerlier approved these changes

2021-06-21 12:38 UTC, jdesboeufs requested changes

2021-06-21 12:38 UTC, jdesboeufs commented on lib/models/base-locale.js
> +async function checkIfBALExists(codeCommune, userEmail) {
À renommer plutôt sous la forme `findByCommuneAndEmail`

2021-06-21 12:38 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  throw new Error('Code commune & email obligatoires')
Mieux vaut faire ce test au début, et avoir l'essentiel du code en dehors du bloc `if`

2021-06-21 12:38 UTC, jdesboeufs commented on lib/routes/__tests__/base-locale.js
> +  t.is(response.status, 500)
On attend plutôt une 400 pour ce type d'erreur

2021-06-21 12:38 UTC, jdesboeufs commented on lib/routes/__tests__/base-locale.js
> +  t.is(response.status, 201)
200. 201 c'est pour les POST.

2021-06-21 12:38 UTC, jdesboeufs commented on lib/routes/index.js
> +    res.status(201).send(exisitingBasesLocales)
200

2021-06-21 12:38 UTC, jdesboeufs commented on lib/routes/index.js
> +    const exisitingBasesLocales = await BaseLocale.checkIfBALExists(req.query.codeCommune, req.query.userEmail)
Gérer les paramètres ici pour la 400.

2021-06-21 14:18 UTC, jdesboeufs approved these changes

2021-06-21 18:49 UTC, merged