Ajout de la propriété certifie aux adresses (numero, toponyme)
etalab/api-bal pull request #288
Opened 2021-07-23 09:25 UTC by cedric-famibelle-pronzola

### - Ajout de la propriété `certifie` :
- au modèle `Numero`
- à l'export `geojson` et `csv`
- au modèle `Toponyme`

### - Mise à jour des tests

### - Création d'un script de migration

2021-07-26 09:14 UTC, tmerlier requested changes

2021-07-26 09:14 UTC, tmerlier commented on lib/export/csv-bal.js
> +        nomVoie: t.nom
Pourquoi la suppression de `parcelles` ?

2021-07-26 09:16 UTC, cedric-famibelle-pronzola commented on lib/export/csv-bal.js
> +        nomVoie: t.nom
ah. involontaire

2021-07-30 14:19 UTC, GllmR approved these changes

2021-08-18 15:50 UTC, tmerlier requested changes

2021-08-18 15:50 UTC, tmerlier commented on lib/models/base-locale.js
> +async function getCommune(idBal, codeCommune) {
Il se préférable de vérifié que le `codeCommune` existe bien pour cette BAL afin de renvoyer une erreur le cas échéant.

2021-08-18 15:50 UTC, tmerlier commented on lib/models/base-locale.js
> +    {$set: {certifie, _updated: now}}
Est-ce qu'il ne serait pas mieux de déplacer `_updated: now` avec les autres ?

2021-08-18 15:50 UTC, tmerlier commented on lib/models/numero.js
> +}
Cette méthode à plus sa place comme helper générique plutôt que de le réserver à `Numero`.

2021-08-18 15:50 UTC, tmerlier commented on lib/models/voie.js
> +  const voie = await mongo.db.collection('voies').findOne({_id: mongo.parseObjectID(id)})
Il gérer le cas où aucune voie ne correspond à cet id.

2021-08-30 13:49 UTC, tmerlier commented on lib/models/voie.js
> +  const voie = await mongo.db.collection('voies').findOne({_id: mongo.parseObjectID(id)})
Inutile, cette vérification est faite dans `app.param`.

2021-08-30 13:55 UTC, tmerlier approved these changes

2021-09-02 08:00 UTC, jdesboeufs commented on lib/util/mongo.js
> +    idsList.forEach(id => {
Utilise `.map()` c'est plus simple, et je doute que cette fonction soit utile du coup.

2021-09-03 15:21 UTC, jdesboeufs requested changes
Il manque l'import du nouveau champ.

2021-09-03 15:21 UTC, jdesboeufs commented on lib/export/csv-bal.js
> +  return certifie === undefined ? '' : (certifie ? '1' : '0')
Si `certifie === null` => '0'

2021-09-06 11:53 UTC, jdesboeufs approved these changes

2021-09-06 12:02 UTC, merged